### ISSUE TITLE
Layout issue when background value is too long

### ISSUE THREAD

**Issue by wizardzloy** [storybooks/addon-backgrounds#24]
<img width="456" alt="screenshot 2016-10-17 16 50 24" src="https://cloud.githubusercontent.com/assets/1524432/19442569/ff847c8a-9489-11e6-9835-772d2792d951.png">

**Comment by Djspaceg** [comment]
I'd like to _second_ this request. Adding the CSS `word-break: break-word;` would allow the long URLs to be force-wrapped. Quick one line fix. :D 

Non-wrapped URL
<img width="588" alt="screen shot 2016-12-05 at 9 59 43 am" src="https://cloud.githubusercontent.com/assets/386529/20896383/568aa6d0-bad2-11e6-9686-be2c1dce1706.png">

Wrapped URL with `word-break: break-word;`
<img width="578" alt="screen shot 2016-12-05 at 10 03 54 am" src="https://cloud.githubusercontent.com/assets/386529/20896405/721a1d90-bad2-11e6-84b6-93b592e87e0a.png">

**Comment by jbaxleyiii** [comment]
@Djspaceg would you be able to open a PR for that? I think that is a great adjustment!

**Comment by mariyanang** [comment]
do you plan to deploy this fix soon?

**Comment by ndelangen** [comment]
This has not yet been released? If not, This will be released tonight!
