### ISSUE TITLE
Support all background properties

### ISSUE THREAD

**Issue by ericclemmons** [storybooks/addon-backgrounds#25]
Support `value` still, but also support:

- `backgroundImage`
- `backgroundSize`
- etc.

This way we can do things like create a grid:
> http://codepen.io/anon/pen/VvPWvv

**Comment by ndelangen** [comment]
Use the background shorthand, it can do everything you want:
https://codepen.io/storybook/pen/owyvYr

Let me know when you have a use case that really requires this. 👍
