### ISSUE TITLE
Refactor into plain JS (remove typescript)

### ISSUE THREAD

**Issue by ndelangen** [storybooks/addon-backgrounds#33]
I want to merge this into the main repo, and introducing typescript into the main repo is a bad idea at this point.

**Comment by ndelangen** [comment]
Typescript has had some major releases in the meanwhile, I've tried updating, but i know very little of typescript and the changes they went through, and got stuck.

**Comment by psimyn** [comment]
I've just had a try at this, will create PR soon

**Comment by ndelangen** [comment]
Awesome @psimyn !
