### ISSUE TITLE
Move into main repo

### ISSUE THREAD

**Issue by ndelangen** [storybooks/addon-backgrounds#36]

**Comment by KaySackey** [comment]
Does this mean it'll be available in storybooks/addons ?

**Comment by ndelangen** [comment]
This means I will merge this repo into https://github.com/storybooks/storybook

**Comment by Hypnosphi** [comment]
Should we add deprecation notice for this repo (and others that are merged into main one)?

**Comment by ndelangen** [comment]
Yes, good point @Hypnosphi
